name: facture_app
description: A new Flutter project.
publish_to: 'none' # Ce projet n'est pas destiné à être publié sur pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Formatage dates et nombres
  intl: ^0.19.0

  # UI & Icônes
  cupertino_icons: ^1.0.8
  google_fonts: ^6.0.0
  flutter_screenutil: ^5.6.1
  flutter_svg: ^2.0.7
  flutter_animate: ^4.5.0
  fluttertoast: ^8.2.1

  # Firebase
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  google_sign_in: ^6.1.5
  cloud_firestore: ^5.6.10
  firebase_storage: ^12.4.8

  # PDF & fichiers
  pdf: ^3.10.5
  path_provider: ^2.1.2
  uuid: ^4.2.1

  # Google APIs
  googleapis: ^13.1.0
  http: ^1.1.0
  # Share et ouverture de fichiers
  share_plus: ^10.0.2
  open_file: ^3.3.2
  
  # Import/Export CSV et Excel
  file_picker: ^8.1.2
  csv: ^6.0.0
  excel: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  # ios: true
  image_path: "assets/Logo_app.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
